TEXTS = {
    "ru": {
        "choose_lang": "Выберите язык / Tilni tanlang:",
        "welcome": "👋 Привет! Я бот для бронирования переговорной комнаты.\n\nВыберите действие:",
        "choose_date": "📅 Выберите дату бронирования:",
        "choose_time_start": "🕐 *Выберите время начала:*",
        "choose_time_end": "🕕 *Выберите время окончания:*",
        "date_chosen": "📅 Дата выбрана: *{date}*",
        "time_start_chosen": "✅ Начало: *{time}*",
        "time_end_chosen": "✅ Конец: *{time}*",
        "enter_comment": "💬 Введите тему встречи и нажмите кнопку подтверждения:",
        "confirm_btn": "✅ Подтвердить",
        "booking_confirmed": "✅ *Бронирование подтверждено!*\n\n🆔 ID: `{id}`\n📅 Дата: {date}\n🕐 Время: {start} — {end}\n💬 Тема: {comment}",
        "my_bookings": "📋 *Ваши бронирования:*\n\n",
        "no_bookings": "📭 У вас нет активных бронирований.",
        "choose_date_view": "📆 Выберите дату для просмотра броней:",
        "no_bookings_date": "📭 На *{date}* бронирований нет. Комната свободна! 🟢",
        "bookings_date": "📆 *Бронирования на {date}:*\n\n",
        "choose_cancel": "❌ Выберите бронирование для отмены:",
        "cancel_confirmed": "✅ Бронирование `{id}` отменено.",
        "cancel_failed": "❌ Не удалось отменить бронирование.",
        "cancelled": "Действие отменено.",
        "select_action": "Выберите действие:",
        "time_busy": "❌ *{start}–{end}* уже занято!\n\n📅 Дата: *{date}*\n\n🕐 *Выберите другое время начала:*",
        "btn_book": "📅 Забронировать",
        "btn_cancel": "❌ Отменить бронь",
        "btn_my": "📋 Мои брони",
        "btn_day": "📆 Брони на день",
        "btn_back": "🔙 Назад",
        "btn_forward": "▶️ Вперёд",
        "btn_prev": "◀️ Назад",
    },
    "uz": {
        "choose_lang": "Выберите язык / Tilni tanlang:",
        "welcome": "👋 Салом! Мен йиғилиш хонасини бронлаш ботиман.\n\nАмални танланг:",
        "choose_date": "📅 Бронлаш санасини танланг:",
        "choose_time_start": "🕐 *Бошланиш вақтини танланг:*",
        "choose_time_end": "🕕 *Тугаш вақтини танланг:*",
        "date_chosen": "📅 Сана танланди: *{date}*",
        "time_start_chosen": "✅ Бошланиш: *{time}*",
        "time_end_chosen": "✅ Тугаш: *{time}*",
        "enter_comment": "💬 Учрашув мавзусини киритинг ва тасдиқлаш тугмасини босинг:",
        "confirm_btn": "✅ Тасдиқлаш",
        "booking_confirmed": "✅ *Бронлаш тасдиқланди!*\n\n🆔 ID: `{id}`\n📅 Сана: {date}\n🕐 Вақт: {start} — {end}\n💬 Мавзу: {comment}",
        "my_bookings": "📋 *Сизнинг бронларингиз:*\n\n",
        "no_bookings": "📭 Сизда фаол бронлар йўқ.",
        "choose_date_view": "📆 Бронларни кўриш учун санани танланг:",
        "no_bookings_date": "📭 *{date}* да бронлар йўқ. Хона бўш! 🟢",
        "bookings_date": "📆 *{date} да бронлар:*\n\n",
        "choose_cancel": "❌ Бекор қилиш учун бронни танланг:",
        "cancel_confirmed": "✅ Бронлаш `{id}` бекор қилинди.",
        "cancel_failed": "❌ Бронлашни бекор қилиб бўлмади.",
        "cancelled": "Амал бекор қилинди.",
        "select_action": "Амални танланг:",
        "time_busy": "❌ *{start}–{end}* банд!\n\n📅 Сана: *{date}*\n\n🕐 *Бошқа вақтни танланг:*",
        "btn_book": "📅 Бронлаш",
        "btn_cancel": "❌ Бронни бекор қилиш",
        "btn_my": "📋 Менинг бронларим",
        "btn_day": "📆 Кунлик бронлар",
        "btn_back": "🔙 Орқага",
        "btn_forward": "▶️ Олдинга",
        "btn_prev": "◀️ Орқага",
    }
}


def t(lang: str, key: str, **kwargs) -> str:
    text = TEXTS.get(lang, TEXTS["ru"]).get(key, key)
    return text.format(**kwargs) if kwargs else text
